#config_version=6


# As you add coils, you will define their name, number on the board, default_pulse.

# Visit https://docs.missionpinball.org/en/latest/mechs/coils/ for additional information.



coils:

#Board 3208

#Trough

  c_trough_eject_coil:
    number: 3208-1
    default_pulse_ms: 15

#Slings & Pops

  c_right_sling:
    number: 3208-6
    default_pulse_ms: 25

  c_left_sling:
    number: 3208-7
    default_pulse_ms: 25
    
  c_pop_bumper:
    number: 1616-5
    default_pulse_ms: 25
    
  c_low_pop_bumper:
    number: 1616-7
    default_pulse_ms: 25

#Plunger

  c_auto_plunger:
    number: 3208-0
    default_pulse_ms: 15

#Flippers

  c_flipper_right_full:
    number: 3208-5
    default_pulse_ms: 30

  c_flipper_right_hold:
    number: 3208-4
    default_hold_power: .125
    
  c_flipper_upper_full:
    number: 1616-0
    default_pulse_ms: 30

  c_flipper_upper_hold:
    number: 1616-1
    default_hold_power: .125
    
  c_flipper_left_full:
    number: 3208-3
    default_pulse_ms: 30

  c_flipper_left_hold:
    number: 3208-2
    default_hold_power: .125
    
#Diverters

#  c_rdiverter:
#    number: 0804-0
#    default_pulse_ms: 35

#Kickers and VUK

  c_left_kicker:
    number: 1616-3
    default_pulse_ms: 35

  c_return_kicker:
    number: 1616-6
    default_pulse_ms: 25

  c_pitstop_vuk:
    number: 1616-2
    default_pulse_ms: 20

#  c_left_vuk:
#    number: 1616-7
#    default_pulse_ms: 20

#Drop Targets

  c_drop_bank:
    number: 1616-4
    default_pulse_ms: 30





#Autofire devices are defined here by switch and what coil is cycled when that switch is active.

autofire_coils:

  slingshot_left:
    coil: c_left_sling
    switch: s_left_sling

  slingshot_right:
    coil: c_right_sling
    switch: s_right_sling
    
  pop_bumper:
    coil: c_pop_bumper
    switch: s_pop_bumper
    
  low_pop_bumper:
    coil: c_low_pop_bumper
    switch: s_low_pop_bumper

  left_kicker:
    coil: c_left_kicker
    switch: s_left_kicker
